site_name: gamesense_docs
nav:
  - Home: index.md
  - For users:
    - Getting Started:  ./for_users/getting_started.md
    - Features:
      - Legitbot:     ./for_users/features/legitbot.md
      - Ragebot:      ./for_users/features/ragebot.md
      - Antiaim:      ./for_users/features/antiaim.md
      - Visuals:      ./for_users/features/visuals.md
      - Misc:         ./for_users/features/misc.md
      - Settings:     ./for_users/features/settings.md
      - Skinchanger:  ./for_users/features/skinchanger.md
      - Playerlist:   ./for_users/features/playerlist.md
    - Common issues & Troubleshooting: ./for_users/common_issues_and_troubleshooting.md
  - For developers:
    - Getting Started:  ./for_developers/getting_started.md
    - API:
      - _G:               ./for_developers/api/_G.md
      - bit:              ./for_developers/api/bit.md
      - client:           ./for_developers/api/client.md
      - config:           ./for_developers/api/config.md
      - cvar{}:           ./for_developers/api/cvar{}.md
      - database:         ./for_developers/api/database.md
      - entity:           ./for_developers/api/entity.md
      - globals:          ./for_developers/api/globals.md
      - json:             ./for_developers/api/json.md
      - materialsystem:   ./for_developers/api/materialsystem.md
      - materialsystem{}: ./for_developers/api/materialsystem{}.md
      - ffi:              ./for_developers/api/ffi.md
      - vector{}:         ./for_developers/api/vector{}.md
      - panorama:         ./for_developers/api/panorama.md
      - plist:            ./for_developers/api/plist.md
      - renderer:         ./for_developers/api/renderer.md
      - ui:               ./for_developers/api/ui.md
    - Events:         ./for_developers/events/events.md
    - Netprops:       ./for_developers/netprops.md
    - Tips & Tricks:  ./for_developers/tips_and_tricks.md
theme:
  name: material
  palette:
    scheme: gamesense
  features:
  - navigation.instant
  - navigation.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details